# Generated by Django 6.0.2 on 2026-02-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель велосипеда')),
                ('parts_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость запчастей')),
                ('labor_hours', models.PositiveIntegerField(verbose_name='Часы работы')),
                ('status', models.CharField(default='Принят', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
