# Generated by Django 6.0.2 on 2026-02-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги/запчасти')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Клиент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='В работе', max_length=20, verbose_name='Статус')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.serviceitem', verbose_name='Услуга/Запчасть')),
            ],
        ),
    ]
