# Generated by Django 6.0.2 on 2026-02-25 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_bicyclemodel_serviceitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя/Название')),
                ('type', models.CharField(choices=[('SUP', 'Поставщик'), ('CLI', 'Клиент')], max_length=3, verbose_name='Тип')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Деталь/Запчасть')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки')),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('min_limit', models.PositiveIntegerField(default=3, verbose_name='Мин. порог')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=3, verbose_name='Тип')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.contractor')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.product', verbose_name='Товар')),
            ],
        ),
        migrations.DeleteModel(
            name='Bicycle',
        ),
        migrations.DeleteModel(
            name='BicycleModel',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ServiceItem',
        ),
    ]
