# Generated by Django 6.0.2 on 2026-02-25 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_category_contractor_product_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'История операций'},
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='type',
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_type',
            field=models.CharField(choices=[('SUPPLIER', 'Поставщик материала'), ('CUSTOMER', 'Покупатель мебели')], default='SUPPLIER', max_length=10, verbose_name='Тип партнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название/ФИО'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.contractor', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INBOUND', 'Закупка (Приход)'), ('OUTBOUND', 'Продажа (Расход)'), ('PROD_IN', 'Производство (Выпуск готовой мебели)'), ('PROD_OUT', 'Производство (Списание материалов)')], max_length=10, verbose_name='Тип операции'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул/Код')),
                ('item_type', models.CharField(choices=[('MATERIAL', 'Материал/Сырье'), ('PRODUCT', 'Готовая продукция')], default='MATERIAL', max_length=10, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Остаток на складе')),
                ('unit', models.CharField(default='шт.', max_length=10, verbose_name='Ед. измерения')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена закупки')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи')),
                ('min_limit', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Мин. запас')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объект склада',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workshop.item', verbose_name='Товар/Материал'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
